#define ipconfigUSE_DHCP 0
#define ipconfigHAS_PRINTF 1
#define ipconfigHAS_DEBUG_PRINTF 0
#define configMAC_ADDR0 0x00
#define configMAC_ADDR1 0x0A
#define configMAC_ADDR2 0x35
#define configMAC_ADDR3 0x04
#define configMAC_ADDR4 0xDB
#define configMAC_ADDR5 0x7A
#define configIP_ADDR0 10
#define configIP_ADDR1 88
#define configIP_ADDR2 88
#define configIP_ADDR3 32
#define configGATEWAY_ADDR0 10
#define configGATEWAY_ADDR1 88
#define configGATEWAY_ADDR2 88
#define configGATEWAY_ADDR3 1
#define configNET_MASK0 255
#define configNET_MASK1 255
#define configNET_MASK2 255
#define configNET_MASK3 0
